-- Migration 025: Clean up mock patients generated by disabled migrations
-- This migration removes all patients with MRN- prefix (mock patients)
-- Date: 2025-11-24

DO $$
DECLARE
    deleted_count INTEGER;
BEGIN
    -- Delete all mock patients (MRN- prefix)
    DELETE FROM patients
    WHERE medical_record_number LIKE 'MRN-%';

    GET DIAGNOSTICS deleted_count = ROW_COUNT;

    RAISE NOTICE 'Deleted % mock patients with MRN- prefix', deleted_count;

    -- Show remaining patient count
    RAISE NOTICE 'Remaining patients: %', (SELECT COUNT(*) FROM patients);
END $$;
